import Config

# Configure your database
config :club, Club.ReadRepo,
  username: "postgres",
  password: "postgres",
  database: "club_read_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# EventStore
config :club, Club.EventStore,
  username: "postgres",
  # password: "postgres",
  database: "club_es_dev",
  hostname: "localhost",
  pool_size: 10

config :commanded_audit_middleware, Commanded.Middleware.Auditing.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "club_audit_dev",
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: "5432"

# Scheduler repo
# config :commanded_scheduler, Commanded.Scheduler.Repo,
#   adapter: Ecto.Adapters.Postgres,
#   database: "club_scheduler_dev",
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   pool_size: 1

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :club, ClubWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

if !File.exists?("config/pow_assent.exs"),
  do:
    raise("""
      Pow Assent requires external auth providers settings!
      Please create config/pow_assent_social.exs file.
    """)

import_config("pow_assent.exs")

config :mix_test_watch,
  tasks: [
    "test --trace",
    "credo --strict",
    # "sobelow --verbose"
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :club, ClubWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/club_web/{live,views}/.*(ex)$",
      ~r"lib/club_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
